language: java
install: "./gradlew clean"
script: "./gradlew assemble"
deploy:
  provider: releases
  skip_cleanup: true
#  api_key:
#    secure: gb2FJHkI9U3M3WG2tmc42I6yfHkXI7CBGm/NQ6YMCS5tXm8FecCSn13ab3zUdC02tgPtrV6P3NsiDT7c6ZP8c1ioUeWN7khXkck31GUFuse3GwbpYGslnOas5HKajJQahfSWPGNT7DOb8jwbcMNi446Fbpu0mPjrAElc7eyga/ODUf0XIggtzQTWUl9ioJug8GVVGkemJTVsDE2LI6Rtyz5ghjsJIUZKMcXHVBS1xQM4ZxkMKr5SUuQSRSuppsqrNKgdTQUfjdlbHBLA5qFscA9PqF5e8jqSKA1KYblRD9otv45+F96qX9b3d84kv7oBr9FmKZpxNFF8cc3SKJyyeFZCBYvP9rwh5itCNARQNkRltITf2BJElvj3GVCv84fl1e54dI/cbP2zuXvJqPsyHYg6A3U/lkmP3atxvTcbeGYXHeUkSxzNGTPl6DJFeKdshhDVBr8NUlGLulwIEtjeiVUlQlEFRwofC2e1JKn2uikiD6cqYlkBrQKh0V0LLhM8cPer2NGfq/lIL8YcLuRMJcuFS3/RdZyJt3Ystz/7cjK0EpunpEuIRdwglxot7mA5Q9BqpH3BhcEFhJ16LvCKFH3xIVoRWySEwgBmACozsQW4fJ9qSjPFaoQhl4DachVC9muDnTaf86f1b7VGpMTZkVafpPmXhYMwXJBQC36P/GA=
  file_glob: true
  file: build/libs/*
  on:
    repo: peh/grafana-jenkins-micro
  username: peh
  password:
    secure: FAliOmdebapyMnCoAc50+omEx+SKvzGQgtidpqoEHq4cJJ36gVlP3qRF8cFA8DeowDWXddoy9ihftDsq6JIKT3F8LAwkpQbjBL10vlCZ0hMXKsxWrqWaaprft0jDgwpuSFBCQnjBSGqypTtH16ykKWOxH00YY4bJOLbJktqUuqNOsuu1KAliAjeBdZn95aayjcCh0y62711+1++DrhhkW0OjN9D/FBinp36ZDZ80oVW38+MBjvB7HR7k6XedbdY6hYxRJXQ3GTivoEVjptow9/8J+Jg0RvlAcdNlnY3/tZX8LxyG9erOZHQIegtqQ68pfeKIPq9qk+fY31PLVtTW1QZpUFm5RfFcmNWAeiuhtLRe7dj2BxGd5cQ3pViTdg22maBkkFgKiTV6ScjOBu/uDbj+Gpz3+w46XfVFzOWtN0i2SqdYLg3+HplZY9EGblObC5op5zxPvj7mjXBP39jGrumlf95aYVPwvSEYn3SvFrrZw9k6VHo4exHPS+o7dvbgGNGL137x4GUVASUHTZttXq/BUcaXhQsjEog2qPeAAdGJ7rLv2zKWj9wuFlV9I8Y6kQYxYLz8byWCdviYohWQInuHbRvlqNaq2pCUZ0f8Q8dtb4xyufUZxUCuODsREZSuJaPZYa3rMJDBwMGXWLpOPxKucD15FBDMmG+4P1PZBCQ=
