language: java
install: "./gradlew clean"
script: "./gradlew assemble"
deploy:
  provider: releases
  api_key:
    secure: gb2FJHkI9U3M3WG2tmc42I6yfHkXI7CBGm/NQ6YMCS5tXm8FecCSn13ab3zUdC02tgPtrV6P3NsiDT7c6ZP8c1ioUeWN7khXkck31GUFuse3GwbpYGslnOas5HKajJQahfSWPGNT7DOb8jwbcMNi446Fbpu0mPjrAElc7eyga/ODUf0XIggtzQTWUl9ioJug8GVVGkemJTVsDE2LI6Rtyz5ghjsJIUZKMcXHVBS1xQM4ZxkMKr5SUuQSRSuppsqrNKgdTQUfjdlbHBLA5qFscA9PqF5e8jqSKA1KYblRD9otv45+F96qX9b3d84kv7oBr9FmKZpxNFF8cc3SKJyyeFZCBYvP9rwh5itCNARQNkRltITf2BJElvj3GVCv84fl1e54dI/cbP2zuXvJqPsyHYg6A3U/lkmP3atxvTcbeGYXHeUkSxzNGTPl6DJFeKdshhDVBr8NUlGLulwIEtjeiVUlQlEFRwofC2e1JKn2uikiD6cqYlkBrQKh0V0LLhM8cPer2NGfq/lIL8YcLuRMJcuFS3/RdZyJt3Ystz/7cjK0EpunpEuIRdwglxot7mA5Q9BqpH3BhcEFhJ16LvCKFH3xIVoRWySEwgBmACozsQW4fJ9qSjPFaoQhl4DachVC9muDnTaf86f1b7VGpMTZkVafpPmXhYMwXJBQC36P/GA=
  file: build/libs/jenkins-grafana-build-time-0.1-all.jar
  on:
    repo: peh/grafana-jenkins-micro
