language: java
install: "./gradlew clean"
script: "./gradlew assemble"
deploy:
  provider: releases
  api_key:
    secure: LmKHi0VaMT/k5bD4Y4oQUfMXB5Blgden1bnx60SxPcKWbIc/Z0aLl1GFYQeLLXANA5tAO6i7Tbu5FVA256gkAb3JnjGJp6ME1l8Crz6//6Do/NZAIu5lgYp88+aU9X0dTOB1Qang65DxzeuZpgqaj3JXZKuU53v1/jvZaX01u/KyJgfNSzNbgtfpChwmnKCTBx+mjFIX6DaMB+XQ/kTCa9vYFyi0ZygPvnVnr2GEKGFxa3/+l+DH7fmYPV+T4+mXVDUbbLttS74TnyeYV2SotWmIhTAUgC/51fa/AZqSQwHteFF+hIIduqQhxYqRmj8oWuuufjvmwWFXvUVu896cff/jH4Oaby5ACbOQhl7WScPJPJY7jFscjeONGl+b8zJkkrJdxv/vScYjBmSQDyBYYVw+A1BLyRhjPsuO+2Au5eR7xxgontKfGRjWEYfXYNd8HY6xhH252HsJZN+W/CebAdzmJrTzetUjC7BmbchaInp1qfl6+9A3YU/qBPWzuM979ThmQaoE5z/peLmAlD1iXsb4XsE+eYrmqdk695AHxueU+wm34DZ4E8aA1LLKLIAEw6HbarnZ/+tdwOHdIc7xFEo/jVxET5uQcqaCx4rY3ZflkJfmUjOqwIx1T6GKV6t77uKIej81Kc40uPEivNgGwhGilO/V63vUjNSWAucs9NI=
  file: build/libs/jenkins-grafana-build-time-0.1-all.jar
  on:
    repo: peh/grafana-jenkins-micro
    tags: true
